// Generate an FIR PDF using jsPDF from the structured FIR JSON.
import { jsPDF } from "jspdf";

export type FIR = {
  fir_number: string;
  date_of_report: string;
  time_of_report: string;
  police_station: string;
  complainant: { name: string; age: string; gender: string; address: string; contact: string };
  accused: { name: string; relation: string; address: string; description: string };
  incident: { date: string; time: string; location: string; description: string };
  witnesses: string[];
  applicable_sections: { code: string; section: string; description: string }[];
  digital_evidence_summary: string;
  statement_of_complainant: string;
  draft_disclaimer: string;
};

export function downloadFIRPdf(fir: FIR, evidence?: { hash?: string; cid?: string; txHash?: string }) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  function addPageIfNeeded(extra = 0) {
    if (y + extra > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      y = margin;
    }
  }

  function H1(text: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    addPageIfNeeded(24);
    doc.text(text, pageW / 2, y, { align: "center" });
    y += 22;
  }

  function H2(text: string) {
    addPageIfNeeded(20);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(0, 80, 70);
    doc.text(text, margin, y);
    y += 14;
    doc.setTextColor(0, 0, 0);
  }

  function P(text: string) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    const lines = doc.splitTextToSize(text || "—", pageW - margin * 2);
    for (const line of lines) {
      addPageIfNeeded(14);
      doc.text(line, margin, y);
      y += 13;
    }
  }

  function KV(label: string, value: string) {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    addPageIfNeeded(14);
    doc.text(`${label}:`, margin, y);
    doc.setFont("helvetica", "normal");
    const vx = margin + 110;
    const lines = doc.splitTextToSize(value || "—", pageW - margin - vx);
    doc.text(lines[0] ?? "—", vx, y);
    y += 13;
    for (let i = 1; i < lines.length; i++) {
      addPageIfNeeded(14);
      doc.text(lines[i], vx, y);
      y += 13;
    }
  }

  // Title
  H1("FIRST INFORMATION REPORT (DRAFT)");
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(120, 120, 120);
  doc.text("Generated by SilentWitness · Preliminary draft, subject to police verification", pageW / 2, y, {
    align: "center",
  });
  y += 18;
  doc.setTextColor(0, 0, 0);

  // Header block
  KV("FIR No.", fir.fir_number);
  KV("Date", fir.date_of_report);
  KV("Time", fir.time_of_report);
  KV("Police Station", fir.police_station);
  y += 6;

  H2("1. Complainant");
  KV("Name", fir.complainant.name);
  KV("Age", fir.complainant.age);
  KV("Gender", fir.complainant.gender);
  KV("Address", fir.complainant.address);
  KV("Contact", fir.complainant.contact);
  y += 6;

  H2("2. Accused");
  KV("Name", fir.accused.name);
  KV("Relation", fir.accused.relation);
  KV("Address", fir.accused.address);
  P(fir.accused.description);
  y += 6;

  H2("3. Incident");
  KV("Date", fir.incident.date);
  KV("Time", fir.incident.time);
  KV("Location", fir.incident.location);
  P(fir.incident.description);
  y += 6;

  H2("4. Witnesses");
  if (fir.witnesses.length === 0) P("None reported by complainant.");
  else fir.witnesses.forEach((w, i) => P(`${i + 1}. ${w}`));
  y += 6;

  H2("5. Applicable Sections (Preliminary)");
  if (!fir.applicable_sections.length) P("To be determined by investigating officer.");
  else
    fir.applicable_sections.forEach((s) =>
      P(`• ${s.code} §${s.section} — ${s.description}`)
    );
  y += 6;

  H2("6. Statement of Complainant");
  P(fir.statement_of_complainant);
  y += 6;

  H2("7. Digital Evidence");
  P(fir.digital_evidence_summary);
  if (evidence?.hash) KV("SHA-256", evidence.hash);
  if (evidence?.cid) KV("IPFS CID", evidence.cid);
  if (evidence?.txHash) KV("Anchored Tx", evidence.txHash);
  y += 10;

  // Disclaimer footer
  doc.setDrawColor(180);
  doc.line(margin, y, pageW - margin, y);
  y += 14;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(9);
  doc.setTextColor(90, 90, 90);
  const disc = doc.splitTextToSize(fir.draft_disclaimer, pageW - margin * 2);
  for (const line of disc) {
    addPageIfNeeded(12);
    doc.text(line, margin, y);
    y += 11;
  }

  doc.save(`FIR_${fir.fir_number.replace(/[^a-z0-9_-]/gi, "_")}.pdf`);
}
