/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as ProcessingRouteImport } from './routes/processing'
import { Route as LegalChatRouteImport } from './routes/legal-chat'
import { Route as DisguiseRouteImport } from './routes/disguise'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TamperTestIdRouteImport } from './routes/tamper-test.$id'
import { Route as ExplorerTxRouteImport } from './routes/explorer.$tx'
import { Route as CertificateIdRouteImport } from './routes/certificate.$id'
import { Route as ApiLegalChatRouteImport } from './routes/api/legal-chat'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingRoute = ProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalChatRoute = LegalChatRouteImport.update({
  id: '/legal-chat',
  path: '/legal-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DisguiseRoute = DisguiseRouteImport.update({
  id: '/disguise',
  path: '/disguise',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TamperTestIdRoute = TamperTestIdRouteImport.update({
  id: '/tamper-test/$id',
  path: '/tamper-test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerTxRoute = ExplorerTxRouteImport.update({
  id: '/explorer/$tx',
  path: '/explorer/$tx',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateIdRoute = CertificateIdRouteImport.update({
  id: '/certificate/$id',
  path: '/certificate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLegalChatRoute = ApiLegalChatRouteImport.update({
  id: '/api/legal-chat',
  path: '/api/legal-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/disguise': typeof DisguiseRoute
  '/legal-chat': typeof LegalChatRoute
  '/processing': typeof ProcessingRoute
  '/timeline': typeof TimelineRoute
  '/verify': typeof VerifyRoute
  '/api/legal-chat': typeof ApiLegalChatRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explorer/$tx': typeof ExplorerTxRoute
  '/tamper-test/$id': typeof TamperTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/disguise': typeof DisguiseRoute
  '/legal-chat': typeof LegalChatRoute
  '/processing': typeof ProcessingRoute
  '/timeline': typeof TimelineRoute
  '/verify': typeof VerifyRoute
  '/api/legal-chat': typeof ApiLegalChatRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explorer/$tx': typeof ExplorerTxRoute
  '/tamper-test/$id': typeof TamperTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capture': typeof CaptureRoute
  '/disguise': typeof DisguiseRoute
  '/legal-chat': typeof LegalChatRoute
  '/processing': typeof ProcessingRoute
  '/timeline': typeof TimelineRoute
  '/verify': typeof VerifyRoute
  '/api/legal-chat': typeof ApiLegalChatRoute
  '/certificate/$id': typeof CertificateIdRoute
  '/explorer/$tx': typeof ExplorerTxRoute
  '/tamper-test/$id': typeof TamperTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capture'
    | '/disguise'
    | '/legal-chat'
    | '/processing'
    | '/timeline'
    | '/verify'
    | '/api/legal-chat'
    | '/certificate/$id'
    | '/explorer/$tx'
    | '/tamper-test/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capture'
    | '/disguise'
    | '/legal-chat'
    | '/processing'
    | '/timeline'
    | '/verify'
    | '/api/legal-chat'
    | '/certificate/$id'
    | '/explorer/$tx'
    | '/tamper-test/$id'
  id:
    | '__root__'
    | '/'
    | '/capture'
    | '/disguise'
    | '/legal-chat'
    | '/processing'
    | '/timeline'
    | '/verify'
    | '/api/legal-chat'
    | '/certificate/$id'
    | '/explorer/$tx'
    | '/tamper-test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptureRoute: typeof CaptureRoute
  DisguiseRoute: typeof DisguiseRoute
  LegalChatRoute: typeof LegalChatRoute
  ProcessingRoute: typeof ProcessingRoute
  TimelineRoute: typeof TimelineRoute
  VerifyRoute: typeof VerifyRoute
  ApiLegalChatRoute: typeof ApiLegalChatRoute
  CertificateIdRoute: typeof CertificateIdRoute
  ExplorerTxRoute: typeof ExplorerTxRoute
  TamperTestIdRoute: typeof TamperTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing': {
      id: '/processing'
      path: '/processing'
      fullPath: '/processing'
      preLoaderRoute: typeof ProcessingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-chat': {
      id: '/legal-chat'
      path: '/legal-chat'
      fullPath: '/legal-chat'
      preLoaderRoute: typeof LegalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disguise': {
      id: '/disguise'
      path: '/disguise'
      fullPath: '/disguise'
      preLoaderRoute: typeof DisguiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tamper-test/$id': {
      id: '/tamper-test/$id'
      path: '/tamper-test/$id'
      fullPath: '/tamper-test/$id'
      preLoaderRoute: typeof TamperTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer/$tx': {
      id: '/explorer/$tx'
      path: '/explorer/$tx'
      fullPath: '/explorer/$tx'
      preLoaderRoute: typeof ExplorerTxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate/$id': {
      id: '/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/certificate/$id'
      preLoaderRoute: typeof CertificateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/legal-chat': {
      id: '/api/legal-chat'
      path: '/api/legal-chat'
      fullPath: '/api/legal-chat'
      preLoaderRoute: typeof ApiLegalChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptureRoute: CaptureRoute,
  DisguiseRoute: DisguiseRoute,
  LegalChatRoute: LegalChatRoute,
  ProcessingRoute: ProcessingRoute,
  TimelineRoute: TimelineRoute,
  VerifyRoute: VerifyRoute,
  ApiLegalChatRoute: ApiLegalChatRoute,
  CertificateIdRoute: CertificateIdRoute,
  ExplorerTxRoute: ExplorerTxRoute,
  TamperTestIdRoute: TamperTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
